# Generated by Django 5.2.4 on 2025-09-13 14:58

import apps.main.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.main.models.make_article_image_path, verbose_name='Фотография')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article', verbose_name='Статья')),
            ],
        ),
    ]
